-- =============================================
-- 비파괴 추가 마이그레이션
-- 기존 users / memos / custom_schedule 데이터는 그대로 두고,
-- 필요한 새 테이블만 추가합니다.
-- =============================================

create extension if not exists pgcrypto;

create table if not exists public.timetable_entries (
    id bigint generated by default as identity primary key,
    teacher_name text not null,
    day text not null check (day in ('월', '화', '수', '목', '금')),
    period integer not null check (period between 1 and 9),
    subject text default '',
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    unique (teacher_name, day, period)
);

create index if not exists idx_timetable_entries_teacher_name
    on public.timetable_entries (teacher_name);

create index if not exists idx_timetable_entries_day_period
    on public.timetable_entries (day, period);

create table if not exists public.academic_calendar (
    date date primary key,
    event text not null,
    updated_at timestamptz default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_timetable_entries_updated_at on public.timetable_entries;
create trigger trg_timetable_entries_updated_at
before update on public.timetable_entries
for each row
execute function public.set_updated_at();

drop trigger if exists trg_academic_calendar_updated_at on public.academic_calendar;
create trigger trg_academic_calendar_updated_at
before update on public.academic_calendar
for each row
execute function public.set_updated_at();
